const { body, validationResult } = require("express-validator");
const { addTrainer } = require("../db/queries");

const listOfPokemon = [
  "bulbasaur",
  "ivysaur",
  "venusaur",
  "charmander",
  "charmeleon",
  "charizard",
  "squirtle",
  "wartortle",
  "blastoise",
  "caterpie",
  "metapod",
  "butterfree",
  "weedle",
  "kakuna",
  "beedrill",
  "pidgey",
  "pidgeotto",
  "pidgeot",
  "rattata",
  "raticate",
  "spearow",
  "fearow",
  "ekans",
  "arbok",
  "pikachu",
  "raichu",
  "sandshrew",
  "sandslash",
  "nidoran-f",
  "nidorina",
  "nidoqueen",
  "nidoran-m",
  "nidorino",
  "nidoking",
  "clefairy",
  "clefable",
  "vulpix",
  "ninetales",
  "jigglypuff",
  "wigglytuff",
  "zubat",
  "golbat",
  "oddish",
  "gloom",
  "vileplume",
  "paras",
  "parasect",
  "venonat",
  "venomoth",
  "diglett",
  "dugtrio",
  "meowth",
  "persian",
  "psyduck",
  "golduck",
  "mankey",
  "primeape",
  "growlithe",
  "arcanine",
  "poliwag",
  "poliwhirl",
  "poliwrath",
  "abra",
  "kadabra",
  "alakazam",
  "machop",
  "machoke",
  "machamp",
  "bellsprout",
  "weepinbell",
  "victreebel",
  "tentacool",
  "tentacruel",
  "geodude",
  "graveler",
  "golem",
  "ponyta",
  "rapidash",
  "slowpoke",
  "slowbro",
  "magnemite",
  "magneton",
  "farfetchd",
  "doduo",
  "dodrio",
  "seel",
  "dewgong",
  "grimer",
  "muk",
  "shellder",
  "cloyster",
  "gastly",
  "haunter",
  "gengar",
  "onix",
  "drowzee",
  "hypno",
  "krabby",
  "kingler",
  "voltorb",
  "electrode",
  "exeggcute",
  "exeggutor",
  "cubone",
  "marowak",
  "hitmonlee",
  "hitmonchan",
  "lickitung",
  "koffing",
  "weezing",
  "rhyhorn",
  "rhydon",
  "chansey",
  "tangela",
  "kangaskhan",
  "horsea",
  "seadra",
  "goldeen",
  "seaking",
  "staryu",
  "starmie",
  "mr-mime",
  "scyther",
  "jynx",
  "electabuzz",
  "magmar",
  "pinsir",
  "tauros",
  "magikarp",
  "gyarados",
  "lapras",
  "ditto",
  "eevee",
  "vaporeon",
  "jolteon",
  "flareon",
  "porygon",
  "omanyte",
  "omastar",
  "kabuto",
  "kabutops",
  "aerodactyl",
  "snorlax",
  "articuno",
  "zapdos",
  "moltres",
  "dratini",
  "dragonair",
  "dragonite",
  "mewtwo",
  "mew",
];

function pokemonToID(name) {
  return listOfPokemon.indexOf(name) + 1;
}

const validatePokemon = [
  body("pokemon1").trim().isIn(listOfPokemon).withMessage(`Pokemon 1 must be part of the suggested list`),
  body("pokemon2").trim().isIn(listOfPokemon).withMessage(`Pokemon 2 must be part of the suggested list`),
  body("pokemon3").trim().isIn(listOfPokemon).withMessage(`Pokemon 3 must be part of the suggested list`),
  body("pokemon4").trim().isIn(listOfPokemon).withMessage(`Pokemon 4 must be part of the suggested list`),
  body("pokemon5").trim().isIn(listOfPokemon).withMessage(`Pokemon 5 must be part of the suggested list`),
  body("pokemon6").trim().isIn(listOfPokemon).withMessage(`Pokemon 6 must be part of the suggested list`),
];
module.exports = {
  get: (req, res) => {
    res.render("trainerView", { title: "Trainers" });
  },

  getCreateTrainer: (req, res) => {
    res.render("createTrainerView", { title: "Create Trainer" });
  },
  postCreateTrainer: [
    validatePokemon,
    (req, res) => {
      const errors = validationResult(req);
      if (!errors.isEmpty()) {
        return res.status(400).render("createTrainerView", { title: "Create Trainer", errors: errors.array() });
      }
      const { trainerName, pokemon1, pokemon2, pokemon3, pokemon4, pokemon5, pokemon6 } = req.body;
      addTrainer(
        trainerName,
        pokemonToID(pokemon1),
        pokemonToID(pokemon2),
        pokemonToID(pokemon3),
        pokemonToID(pokemon4),
        pokemonToID(pokemon5),
        pokemonToID(pokemon6)
      );
      res.redirect("/trainer");
    },
  ],
};
